apiVersion: v1
kind: Pod
metadata:
  name: news-scraper
spec:
#  activeDeadlineSeconds: 1800  # Pod terminates after 30 min
  securityContext:
    runAsUser: 503 # run id command in terminal to get your UID
    runAsGroup: 1132
  containers:
    - name: example-container
      image:  ghcr.io/gangani/kub_temp:main  # image name
      resources:
        requests: # minimum resources
          memory: "16Gi"
          cpu: "8"
        limits: # maximum resources
          memory: "24Gi"
          cpu: "16"
      volumeMounts:
      - name: home
        mountPath: "/app"
      command: ["/bin/sh"]
      stdin: true
      tty: true
  volumes:
  - name: home
    nfs:
      server: 128.239.56.166
      path: /sciclone/home/gchewababarand/repos