apiVersion: v1
kind: Pod
metadata:
  name: browsertrix-crawler
spec:
  securityContext:
    runAsUser: 261440  # Replace with your actual UID
    runAsGroup: 1132    # Replace with your actual GID
  containers:
    - name: browsertrix-crawler-container
      image: webrecorder/browsertrix-crawler:latest  # Use the Browsertrix crawler image
      resources:
        requests:
          memory: "16Gi"
          cpu: "8"
        limits:
          memory: "24Gi"
          cpu: "16"
      volumeMounts:
        - name: crawl-data
          mountPath: "/crawls"  # Mount the crawl data directory to /crawls in the container
        - name: config-dir
          mountPath: "/app"  # Mount the directory where crawl.yml is located (config)
      command: ["/bin/bash", "-c", "docker run -v /crawls:/crawls/ webrecorder/browsertrix-crawler crawl --url https://example.com --generateWACZ --text --collection test"]  # Run the Browsertrix crawl command
      stdin: true
      tty: true
  volumes:
    - name: crawl-data
      nfs:
        server: 128.239.56.166  # Your NFS server
        path: /sciclone/home/gchewababarand/crawls  # Path for storing crawl data
    - name: config-dir
      nfs:
        server: 128.239.56.166  # Your NFS server
        path: /sciclone/home/gchewababarand/repos  # Path for storing configuration files like crawl.yml
